name: Vehicles
version: ${project.version}
main: me.psek.vehicles.Vehicles
api-version: 1.14
depend:
  - ProtocolLib
authors: [ Psek ]
description: car go brrrrrrrrrrrrrrrrrrrrrrrr
commands:
  vehicles:
    description: cool brrrrrrr
    aliases: [vehicles, vehicle, ve, v]
