name: Vehicles
version: ${project.version}
main: me.psek.vehicles.Vehicles
api-version: 1.13
depend:
  - ProtocolLib
authors: [ Psek ]
description: The only vehicle plugin you will ever need!
commands:
  vehicles:
    description: The main command
    aliases: [vehicles, vehicle, ve, v]
  24vs73x501:
    permission-message: no perms